### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by raokars** [EsriUK/OS-Highways-tools#1]
HI, Download the OSMM-Highways.tbx file and added to Toolbox.  the toolbox got added but does not show tools under it. it just shows "OSMM-Highways" that's all.. when I click nothing happens as shown in the attached pic. Am I doing anything wrong?. Help will be much apprecitated. Using ARCGIS 10.3.1 with Data Interoperability Tools installed.

![osmm-highways](https://cloud.githubusercontent.com/assets/6481050/16041153/d8a16670-322b-11e6-89fd-b46f4c143917.png)

**Comment by petermcdaid** [comment]
You will need to ensure the Data Interoperability Extension is enabled for the tools to show. If you go into Customize - Extensions and ensure that it is ticked.
